-- Superseded by 20260322000011_receipt_queue_and_platform_delete.sql
-- which defines the 8-parameter version with receipt queue support.
-- This file is intentionally a no-op to avoid creating a conflicting overload.
